## Module 5: Introduction to NumPy & Pandas


In [2]:
import numpy as np

In [84]:
test = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
test1 = np.arange(1,17)
print(test.ndim)
print(test.shape)
print(test)
print(test1)
print(test1.reshape((2,2,2,2),order='F'))

3
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[[[ 1  9]
   [ 5 13]]

  [[ 3 11]
   [ 7 15]]]


 [[[ 2 10]
   [ 6 14]]

  [[ 4 12]
   [ 8 16]]]]


In [21]:
# create an array
arr = np.array([11, 22, 33, 44])
arr

array([11, 22, 33, 44])

In [22]:
type(arr)

numpy.ndarray

In [23]:
print(arr)

[11 22 33 44]


In [24]:
#shape
arr.shape

(4,)

In [25]:
# 2D array
arr_2d = np.array([[11,22], [33, 44]])
arr_2d

array([[11, 22],
       [33, 44]])

In [26]:
 # shape returns (rows, cols)
arr_2d.shape

(2, 2)

### List Vs Array

In [27]:
a = [1,2,3]
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [28]:
# multiplying list with a number
a*2

[1, 2, 3, 1, 2, 3]

In [29]:
arr*2

array([2, 4, 6])

In [30]:
print(arr)  # no comma in the output

[1 2 3]


In [31]:
a = [1,2,3]
b = [4,5,6]
arr1 = np.array([1,2,3])
arr2 = np.array([11,22,33])
arr1+arr2  # corresponding elements got added


array([12, 24, 36])

In [13]:
a+b  # a.extend(b)

[1, 2, 3, 4, 5, 6]

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [34]:
# shape of an array : (rows, columns)
arr_2d = np.array([[11,22,100], [33, 44,200]])
print(arr_2d)
print(arr_2d.shape)

[[ 11  22 100]
 [ 33  44 200]]
(2, 3)


In [35]:
# array of zeros
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [37]:
# .dtype attribute  returns datatype of an array
arr.dtype


dtype('float64')

In [36]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# dimension of an array: len(shape)
arr_2d.ndim

2

In [39]:
# check type of an array
arr.dtype

dtype('float64')

In [40]:
# how to define datatype of an array
arr = np.array([1,2,3],
              dtype=np.float16)
arr.dtype

dtype('float16')

In [41]:
arr = np.array([1,2,3],
              dtype=float)
arr.dtype

dtype('float64')

In [42]:
# linearly spaces array
np.linspace(1, 50, 7)

array([ 1.        ,  9.16666667, 17.33333333, 25.5       , 33.66666667,
       41.83333333, 50.        ])

In [43]:
np.linspace(1, 50, 10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [46]:
np.linspace(10, 50, 5)

array([10., 20., 30., 40., 50.])

In [52]:
# reshaping
arr1 = np.zeros(8)
print(arr1)

print("reshaping")
arr2 = arr1.reshape((2,4))
print(arr2)

print("reshaping it to 3D array")
arr3 = arr1.reshape((2,2,2))
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0.]
reshaping
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
reshaping it to 3D array
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [48]:
# flatten the array: convering any dimension array to 1D array
arr3.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0.])

### Indexing and slicing

In [53]:
arr = np.array([11, 22, 33, 44])
arr

array([11, 22, 33, 44])

In [54]:
arr[0]   # indexing is same as in the case of sequences

11

In [55]:
arr[-1]

44

In [56]:
# slicing
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
arr[1:5]  # slicing is also same as in the case of sequences


array([22, 33, 44, 55])

In [57]:
arr[2:]

array([33, 44, 55, 66, 77, 88, 99])

In [58]:
arr[:4]

array([11, 22, 33, 44])

### slicing in 2D arrays

In [4]:
arr_2d = np.array([[11, 22, 33, 44], [55, 66, 77, 88], [99, 12, 13, 14],
                  [89,67,68,45]])
arr_2d

array([[11, 22, 33, 44],
       [55, 66, 77, 88],
       [99, 12, 13, 14],
       [89, 67, 68, 45]])

In [6]:
print(arr_2d.ndim)
print(arr_2d.dtype)
print(arr_2d.shape)

2
int32
(4, 4)


In [60]:
# arr[row_slice,col_slice]
arr_2d[1:3,1:3]

array([[66, 77],
       [12, 13]])

In [68]:
# accessing only rows
arr_2d[1:3,]


array([[55, 66, 77, 88],
       [99, 12, 13, 14]])

In [70]:
# accessing columns only
arr_2d[:,1:3]

array([[22, 33],
       [66, 77],
       [12, 13],
       [67, 68]])

In [74]:
arr_2d[::,1:3]  # step is 1

array([[22, 33],
       [66, 77],
       [12, 13],
       [67, 68]])

In [71]:
# using step in 2D array arr[start:stop:step]
arr_2d[1:100000000:2]  # rows 1,3

array([[55, 66, 77, 88],
       [89, 67, 68, 45]])

### array attributes

In [75]:
arr_2d = np.array([[11, 22, 33, 44], [89,67,68,45]])
arr_2d


array([[11, 22, 33, 44],
       [89, 67, 68, 45]])

In [76]:
arr_2d.ndim # dimension

2

In [77]:
arr_2d.shape

(2, 4)

In [78]:
arr_2d.itemsize  # how many bytes for each element of an array

8

In [79]:
arr_2d.dtype

dtype('int64')

In [80]:
# changing dtype
arr_8 = np.array([1,2,3], dtype=np.int8)
arr_8.dtype

dtype('int8')

In [84]:
# empty array(having random values)
np.empty((3,4))

array([[-0.00000000e+000, -0.00000000e+000,  2.96439388e-323,
         0.00000000e+000],
       [ 1.03977794e-312,  1.31370903e-076,  7.78836839e-091,
         3.92320776e+179],
       [ 4.31696423e-038,  8.38667281e+165,  3.99910963e+252,
         8.34402697e-309]])

### Reading and writing array from a text file

In [85]:
arr = np.loadtxt('./data/my_dollar.txt',
                 delimiter='$')
arr


array([[1., 2., 3., 4., 5.],
       [8., 3., 4., 5., 5.],
       [6., 3., 4., 5., 5.],
       [6., 3., 4., 5., 5.],
       [4., 3., 4., 5., 5.]])

In [86]:
arr = np.loadtxt('./data/numpy_data.txt')
arr

array([[1., 2., 3., 4., 5.],
       [8., 3., 4., 5., 5.],
       [6., 3., 4., 5., 5.],
       [6., 3., 4., 5., 5.],
       [4., 3., 4., 5., 5.]])

In [87]:
?np.loadtxt

In [88]:
# skiprows skips rows from the top
arr = np.loadtxt('./data/numpy_data.txt',
                skiprows=2)
arr

array([[6., 3., 4., 5., 5.],
       [6., 3., 4., 5., 5.],
       [4., 3., 4., 5., 5.]])

In [89]:
# usecols
arr = np.loadtxt('./data/numpy_data.txt',
                usecols=(1,2)) # indexes
arr

array([[2., 3.],
       [3., 4.],
       [3., 4.],
       [3., 4.],
       [3., 4.]])

In [90]:
arr = np.loadtxt('./data/numpy_data.txt',
                usecols=(1,2), # indexes
                skiprows=3)
arr

array([[3., 4.],
       [3., 4.]])

### exporting an array to a file


In [91]:
arr_2d

array([[11, 22, 33, 44],
       [89, 67, 68, 45]])

In [92]:
np.savetxt("output_array_batch.txt", arr_2d)

In [93]:
arr_2d.dtype

dtype('int64')

In [96]:
np.savetxt("output_array_batch.txt",
           arr_2d,
          fmt="%d")

# fmt="%.2f"  # upto 2 decimal values

In [97]:
print(np.savetxt.__doc__)


    Save an array to a text file.

    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:

        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4e %+.4ej'` for 3 columns
        * a list of specifiers, one per column - in this case, the real
          and imaginary part must have separate specifiers,
     

# pandas library

## Series

In [98]:
import pandas as pd

In [99]:
ser = pd.Series([11, 22, 33, 44])
ser

0    11
1    22
2    33
3    44
dtype: int64

In [100]:
isinstance(ser, pd.Series)

True

In [101]:
a = [1, 12.34, 'hello']
pd.Series(a)

0        1
1    12.34
2    hello
dtype: object

In [103]:
# using a dict
d = {'name':"Ravi", 'age':3}
pd.Series(d)

name    Ravi
age        3
dtype: object

## DataFrames
- for tabular data

In [86]:
import pandas as pd

In [223]:
dataframe_test = pd.DataFrame([{'a':1,'b':2},{'a':3,'b':4,'c':5}],index=['first','second'])
print(dataframe_test)
#dir(pd.DataFrame)
print("------")
print(dataframe_test.iloc[1])### iloc means index location or index position
print("-------")
print(dataframe_test.loc['second'])###loc means index name,row label
print("--==--=---")
#dataframe_test.loc['first',dataframe_test == 'c'] = 10 -- works but gives warning

#method - 1
#update_value = pd.DataFrame({'c':[50]}, index=['first'])
#dataframe_test.update(update_value)
#print(dataframe_test)

#method - 2
#dataframe_test.loc['second','a'] = 10
#print(dataframe_test)

#method - 3
#dataframe_test.at['first','b'] = 11
#print(dataframe_test)

print("------========---------")
#dir(pd.DataFrame)
#?pd.DataFrame.ix
#?pd.DataFrame.xs
#?pd.DataFrame.update
#?pd.DataFrame.add
#?pd.DataFrame.append
#?pd.DataFrame.iloc
#?pd.DataFrame.loc

#add column
#method - 1
#dataframe_test.loc['first','d'] = 10

#method - 2
#dataframe_test.loc[dataframe_test.index[0],'d'] = 10
print(dataframe_test)

#add row
#method - 1
data_row = pd.DataFrame({'c' : 100},index=['third'])
print(dataframe_test.append(data_row))

#add row
#method - 2
dataframe_test.loc['fourth','b'] = 200
print(dataframe_test)


        a  b    c
first   1  2  NaN
second  3  4  5.0
------
a    3.0
b    4.0
c    5.0
Name: second, dtype: float64
-------
a    3.0
b    4.0
c    5.0
Name: second, dtype: float64
--==--=---
------========---------
        a  b    c
first   1  2  NaN
second  3  4  5.0
          a    b      c
first   1.0  2.0    NaN
second  3.0  4.0    5.0
third   NaN  NaN  100.0
          a      b    c
first   1.0    2.0  NaN
second  3.0    4.0  5.0
fourth  NaN  200.0  NaN


In [195]:
df = pd.DataFrame([11, 22, 33, 44])
df

0
0  11
1  22
2  33
3  44

In [106]:
#list of dictionaries
data = [{'a':1, 'b':2}, {'a':2, 'b':33, 'c':44}]
df = pd.DataFrame(data)
df
# NaN: Not a Number

a   b     c
0  1   2   NaN
1  2  33  44.0

In [107]:
# user defined indexes
data = [{'a':1, 'b':2}, {'a':2, 'b':33, 'c':44}]
df = pd.DataFrame(data, index=['first', 'second'])
df

a   b     c
first   1   2   NaN
second  2  33  44.0

In [108]:
# adding columns
data = [{'a':1, 'b':2}, {'a':2, 'b':33, 'c':44}]
df = pd.DataFrame(data, index=['first', 'second'])
df['d'] = [100, 200] # new column
df

a   b     c    d
first   1   2   NaN  100
second  2  33  44.0  200

In [109]:
# does the index list length have to match the 
# data list length all the time?

# column addition
data = {'one':pd.Series([10,20,30], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40, 50], index=['a', 'b', 'c', 'd', 'aa'])}
df = pd.DataFrame(data)
df

one  two
a   10.0   10
aa   NaN   50
b   20.0   20
c   30.0   30
d    NaN   40

In [110]:
# creating a new column based on the number of rows
df['jyoti'] = [2]*df.shape[0]
df

one  two  jyoti
a   10.0   10      2
aa   NaN   50      2
b   20.0   20      2
c   30.0   30      2
d    NaN   40      2

In [111]:
df.shape

(5, 3)

In [112]:
s = pd.Series([10,20,30])

In [113]:
len(s)

3

In [114]:
df

one  two  jyoti
a   10.0   10      2
aa   NaN   50      2
b   20.0   20      2
c   30.0   30      2
d    NaN   40      2

In [115]:
# delete a column
del df['two']
df

one  jyoti
a   10.0      2
aa   NaN      2
b   20.0      2
c   30.0      2
d    NaN      2

In [116]:
# pop()
deleted_col = df.pop('one')
deleted_col

a     10.0
aa     NaN
b     20.0
c     30.0
d      NaN
Name: one, dtype: float64

In [ ]:
df

## Row selection in a DataFrame
- **loc**[Row_label]: Row label is the user defined named for rows
- **iloc**[Row_Position]: Row position is position of row from the top of the dataframe starting from 0.

In [117]:
data = {'one':pd.Series([10,20,30], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(data)
df

one  two
a  10.0   10
b  20.0   20
c  30.0   30
d   NaN   40

In [118]:
df.loc['b']

one    20.0
two    20.0
Name: b, dtype: float64

In [ ]:
# NOTE: each row/column is a pandas Series()

In [119]:
df.iloc[1]

one    20.0
two    20.0
Name: b, dtype: float64

### accessing column:
1. direct access method
2. loc


In [120]:
df['one']

a    10.0
b    20.0
c    30.0
d     NaN
Name: one, dtype: float64

In [121]:
df[['one', 'two']]

one  two
a  10.0   10
b  20.0   20
c  30.0   30
d   NaN   40

In [122]:
df.loc[:,'one']

a    10.0
b    20.0
c    30.0
d     NaN
Name: one, dtype: float64

In [123]:
df.loc[:,['one', 'two']]  # access multiple columns together

one  two
a  10.0   10
b  20.0   20
c  30.0   30
d   NaN   40

In [124]:
df.iloc[1:3,[0, 1]]  # access multiple columns together

one  two
b  20.0   20
c  30.0   30

In [126]:
df.loc['a':'c',['one', 'two']]  # access multiple columns together

one  two
a  10.0   10
b  20.0   20
c  30.0   30

### Row addition

In [138]:
data = {'one':pd.Series([1,2,3], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd']),
       'three':pd.Series([10,20,30], index=['a', 'b', 'c'])}
df1 = pd.DataFrame(data)
df1

one  two  three
a  1.0   10   10.0
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN

In [139]:
# append(row)
df2 = pd.DataFrame([[11, 12], [13, 14]], columns=['two', 'three'])
df2

two  three
0   11     12
1   13     14

In [170]:
# appending
new_df=df1.append(df2, sort=False)
new_df

one  two  three
a  1.0   10   10.0
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN
0  NaN   11   12.0
1  NaN   13   14.0

In [143]:
new_df.loc['a']

one       1.0
two      10.0
three    10.0
Name: a, dtype: float64

In [144]:
new_df.loc[0]

one       NaN
two      11.0
three    12.0
Name: 0, dtype: float64

In [145]:
df1.iloc[0]

one       1.0
two      10.0
three    10.0
Name: a, dtype: float64

## Importing and exporting

In [146]:
# loading a csv file into a DataFrame
country_df = pd.read_csv('AllCountries.csv')
country_df

Country  LandArea  Population     GDP  Rural  Internet  \
0              Afghanistan    652.86      30.552   665.0   74.1       5.9   
1                  Albania     27.40       2.897  4460.0   44.6      60.1   
2                  Algeria   2381.74      39.208  5361.0   30.5      16.5   
3           American Samoa      0.20       0.055     NaN   12.7       NaN   
4                  Andorra      0.47       0.079     NaN   13.8      94.0   
..                     ...       ...         ...     ...    ...       ...   
210  Virgin Islands (U.S.)      0.35       0.105     NaN    4.9      45.3   
211     West Bank and Gaza      6.02       4.170     NaN   25.2      46.6   
212            Yemen, Rep.    527.97      24.407  1473.0   66.6      20.0   
213                 Zambia    743.39      14.539  1845.0   60.0      15.4   
214               Zimbabwe    386.85      14.150   953.0   67.3      18.5   

     BirthRate  DeathRate  ElderlyPop  LifeExpectancy  FemaleLabor  \
0         34.1        7.8         2.3            60.9         16.2   
1         12.9        6.9        10.7            77.5         51.7   
2         24.3        5.9         4.6            71.0         16.2   
3          NaN        NaN         NaN             NaN          NaN   
4          NaN        NaN         NaN             NaN          NaN   
..         ...        ...         ...             ...          ...   
210       10.7        8.0        16.0            79.6         64.0   
211       30.4        3.5         3.0            73.2         16.1   
212       31.1        7.2         2.9            63.1         26.4   
213       42.8       10.2         2.6            58.1         73.3   
214       31.3        9.0         3.9            59.8         84.8   

     Unemployment  
0             NaN  
1            13.4  
2            11.0  
3             NaN  
4             NaN  
..            ...  
210           NaN  
211          23.0  
212           NaN  
213           7.8  
214          11.1  

[215 rows x 12 columns]

In [147]:
country_df['Country']

0                Afghanistan
1                    Albania
2                    Algeria
3             American Samoa
4                    Andorra
               ...          
210    Virgin Islands (U.S.)
211       West Bank and Gaza
212              Yemen, Rep.
213                   Zambia
214                 Zimbabwe
Name: Country, Length: 215, dtype: object

In [148]:
country_df[['Country', 'LandArea']]

Country  LandArea
0              Afghanistan    652.86
1                  Albania     27.40
2                  Algeria   2381.74
3           American Samoa      0.20
4                  Andorra      0.47
..                     ...       ...
210  Virgin Islands (U.S.)      0.35
211     West Bank and Gaza      6.02
212            Yemen, Rep.    527.97
213                 Zambia    743.39
214               Zimbabwe    386.85

[215 rows x 2 columns]

In [150]:
#print(pd.read_csv.__doc__)

In [151]:
mydf = pd.read_csv('AllCountries.csv',
                   usecols=['Country','LandArea'])
mydf

Country  LandArea
0              Afghanistan    652.86
1                  Albania     27.40
2                  Algeria   2381.74
3           American Samoa      0.20
4                  Andorra      0.47
..                     ...       ...
210  Virgin Islands (U.S.)      0.35
211     West Bank and Gaza      6.02
212            Yemen, Rep.    527.97
213                 Zambia    743.39
214               Zimbabwe    386.85

[215 rows x 2 columns]

In [153]:
# choosing a row as a header(Default None i.e first row)
mydf = pd.read_csv('AllCountries.csv',
                   header=2)  # 3nd row(index 2) as a header
mydf


Albania     27.4   2.897     4460  44.6  60.1  12.9   6.9  \
0                  Algeria  2381.74  39.208   5361.0  30.5  16.5  24.3   5.9   
1           American Samoa     0.20   0.055      NaN  12.7   NaN   NaN   NaN   
2                  Andorra     0.47   0.079      NaN  13.8  94.0   NaN   NaN   
3                   Angola  1246.70  21.472   5783.0  57.5  19.1  44.1  13.9   
4      Antigua and Barbuda     0.44   0.090  13342.0  75.4  63.4  16.5   6.1   
..                     ...      ...     ...      ...   ...   ...   ...   ...   
208  Virgin Islands (U.S.)     0.35   0.105      NaN   4.9  45.3  10.7   8.0   
209     West Bank and Gaza     6.02   4.170      NaN  25.2  46.6  30.4   3.5   
210            Yemen, Rep.   527.97  24.407   1473.0  66.6  20.0  31.1   7.2   
211                 Zambia   743.39  14.539   1845.0  60.0  15.4  42.8  10.2   
212               Zimbabwe   386.85  14.150    953.0  67.3  18.5  31.3   9.0   

     10.7  77.5  51.7  13.4  
0     4.6  71.0  16.2  11.0  
1     NaN   NaN   NaN   NaN  
2     NaN   NaN   NaN   NaN  
3     2.4  51.9  64.5   NaN  
4     7.1  75.8   NaN   NaN  
..    ...   ...   ...   ...  
208  16.0  79.6  64.0   NaN  
209   3.0  73.2  16.1  23.0  
210   2.9  63.1  26.4   NaN  
211   2.6  58.1  73.3   7.8  
212   3.9  59.8  84.8  11.1  

[213 rows x 12 columns]

In [154]:
mydf = pd.read_csv('AllCountries.csv')
mydf

Country  LandArea  Population     GDP  Rural  Internet  \
0              Afghanistan    652.86      30.552   665.0   74.1       5.9   
1                  Albania     27.40       2.897  4460.0   44.6      60.1   
2                  Algeria   2381.74      39.208  5361.0   30.5      16.5   
3           American Samoa      0.20       0.055     NaN   12.7       NaN   
4                  Andorra      0.47       0.079     NaN   13.8      94.0   
..                     ...       ...         ...     ...    ...       ...   
210  Virgin Islands (U.S.)      0.35       0.105     NaN    4.9      45.3   
211     West Bank and Gaza      6.02       4.170     NaN   25.2      46.6   
212            Yemen, Rep.    527.97      24.407  1473.0   66.6      20.0   
213                 Zambia    743.39      14.539  1845.0   60.0      15.4   
214               Zimbabwe    386.85      14.150   953.0   67.3      18.5   

     BirthRate  DeathRate  ElderlyPop  LifeExpectancy  FemaleLabor  \
0         34.1        7.8         2.3            60.9         16.2   
1         12.9        6.9        10.7            77.5         51.7   
2         24.3        5.9         4.6            71.0         16.2   
3          NaN        NaN         NaN             NaN          NaN   
4          NaN        NaN         NaN             NaN          NaN   
..         ...        ...         ...             ...          ...   
210       10.7        8.0        16.0            79.6         64.0   
211       30.4        3.5         3.0            73.2         16.1   
212       31.1        7.2         2.9            63.1         26.4   
213       42.8       10.2         2.6            58.1         73.3   
214       31.3        9.0         3.9            59.8         84.8   

     Unemployment  
0             NaN  
1            13.4  
2            11.0  
3             NaN  
4             NaN  
..            ...  
210           NaN  
211          23.0  
212           NaN  
213           7.8  
214          11.1  

[215 rows x 12 columns]

In [155]:
mydf = mydf.set_index('Country')
mydf

LandArea  Population     GDP  Rural  Internet  \
Country                                                                
Afghanistan              652.86      30.552   665.0   74.1       5.9   
Albania                   27.40       2.897  4460.0   44.6      60.1   
Algeria                 2381.74      39.208  5361.0   30.5      16.5   
American Samoa             0.20       0.055     NaN   12.7       NaN   
Andorra                    0.47       0.079     NaN   13.8      94.0   
...                         ...         ...     ...    ...       ...   
Virgin Islands (U.S.)      0.35       0.105     NaN    4.9      45.3   
West Bank and Gaza         6.02       4.170     NaN   25.2      46.6   
Yemen, Rep.              527.97      24.407  1473.0   66.6      20.0   
Zambia                   743.39      14.539  1845.0   60.0      15.4   
Zimbabwe                 386.85      14.150   953.0   67.3      18.5   

                       BirthRate  DeathRate  ElderlyPop  LifeExpectancy  \
Country                                                                   
Afghanistan                 34.1        7.8         2.3            60.9   
Albania                     12.9        6.9        10.7            77.5   
Algeria                     24.3        5.9         4.6            71.0   
American Samoa               NaN        NaN         NaN             NaN   
Andorra                      NaN        NaN         NaN             NaN   
...                          ...        ...         ...             ...   
Virgin Islands (U.S.)       10.7        8.0        16.0            79.6   
West Bank and Gaza          30.4        3.5         3.0            73.2   
Yemen, Rep.                 31.1        7.2         2.9            63.1   
Zambia                      42.8       10.2         2.6            58.1   
Zimbabwe                    31.3        9.0         3.9            59.8   

                       FemaleLabor  Unemployment  
Country                                           
Afghanistan                   16.2           NaN  
Albania                       51.7          13.4  
Algeria                       16.2          11.0  
American Samoa                 NaN           NaN  
Andorra                        NaN           NaN  
...                            ...           ...  
Virgin Islands (U.S.)         64.0           NaN  
West Bank and Gaza            16.1          23.0  
Yemen, Rep.                   26.4           NaN  
Zambia                        73.3           7.8  
Zimbabwe                      84.8          11.1  

[215 rows x 11 columns]

In [156]:
mydf.loc['Zambia']

LandArea           743.390
Population          14.539
GDP               1845.000
Rural               60.000
Internet            15.400
BirthRate           42.800
DeathRate           10.200
ElderlyPop           2.600
LifeExpectancy      58.100
FemaleLabor         73.300
Unemployment         7.800
Name: Zambia, dtype: float64

In [160]:
# exporting a dataframe to a file
mydf = pd.read_csv('AllCountries.csv')
mydf.to_csv('output.csv',
            index=None,
            header=None)

In [ ]:
# refer paramster "sep"
# df = pd.read_csv('anand.txt', sep='#', header=None)
#df

### Loading an excel file
- pd.read_excel()

In [161]:
import pandas as pd
data_xls = pd.read_excel("./data/KRA_excel.xlsx")
data_xls

KRAs  \
0  Support your Manager for Project Delivery - Re...   
1  Work ethics\nIt includes professional conduct,...   

                                              Column   ABC  
0  Support your Manager for Project Delivery - Re...  4000  
1                                               1000  3000

### exporting a dataframe to an excel file

In [162]:
data_xls.to_excel('excel_out.xlsx')

### row labels can be duplicated

In [184]:
data = {'one':pd.Series([1,2,3], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd'])}
df1 = pd.DataFrame(data)
df1

one  two
a  1.0   10
b  2.0   20
c  3.0   30
d  NaN   40

In [185]:
# append(row)
df2 = pd.DataFrame([11, 22, 33], index=['a','b', 'c'])
df2

0
a  11
b  22
c  33

In [187]:
# notice that row labels 'a', 'b' and 'c' are duplicated.
df3= df1.append(df2)
df3

one   two     0
a  1.0  10.0   NaN
b  2.0  20.0   NaN
c  3.0  30.0   NaN
d  NaN  40.0   NaN
a  NaN   NaN  11.0
b  NaN   NaN  22.0
c  NaN   NaN  33.0

In [189]:
df3.loc['a']  # duplicated row label

one   two     0
a  1.0  10.0   NaN
a  NaN   NaN  11.0

In [190]:
df3.iloc[0]  # but index position can't be duplicated

one     1.0
two    10.0
0       NaN
Name: a, dtype: float64